---
- hosts: masters
  run_once: true
  tasks:

  # Create a namespace using inline yaml:
  - kubectl_apply:
      kubeconfig:
        # Kubeconfig file on the remote host:
        file: /etc/origin/master/admin.kubeconfig
      namespace: default
      # You can specify your kubernetes config inline if desired. The | is important here:
      inline: |
        kind: "Namespace"
        apiVersion: v1
        metadata:
          name: testnamespace
    register: ns_apply_reg

  - debug: var=ns_apply_reg

  # Use a kubeconfig and configmap definition from the local control host filesystem:
  - set_fact:
      local_kubeconfig: "{{ lookup('file', 'admin.kubeconfig') }}"
      configmap: "{{ lookup('file', 'configmap.yml') }}"

  - kubectl_apply:
      kubeconfig:
        inline: "{{ local_kubeconfig }}"
      namespace: default
      inline: "{{ configmap }}"
    register: ns_apply_reg

  - debug: var=ns_apply_reg


